import { escapeHtml } from "./ui.ts";

export function reporterPage(title: string, body: string, username: string, nonce: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} · Nexus</title><link rel="stylesheet" href="/assets/design-tokens.css"></head><body><header class="header"><a href="/tickets"><strong>Nexus</strong></a><nav aria-label="Main navigation"><a href="/tickets">Tickets</a> <button class="button" type="button" data-logout>Log out</button></nav><span class="worker">${escapeHtml(username)}</span></header><main class="main">${body}</main><script nonce="${escapeHtml(nonce)}">${reporterScript()}</script></body></html>`;
}

export function reporterScript() {
  return `
    const csrfCookie=document.cookie.match(/(?:^|;\\s*)dcc_csrf=([^;]*)/);let csrf=sessionStorage.getItem("dccCsrf")||(csrfCookie?decodeURIComponent(csrfCookie[1]):"");
    fetch("/api/session").then(async response=>{if(response.status===401)return location.assign("/login");const value=response.headers.get("x-csrf-token");if(value){csrf=value;sessionStorage.setItem("dccCsrf",value)}}).catch(()=>{});
    document.querySelector("[data-logout]")?.addEventListener("click",async()=>{await fetch("/api/logout",{method:"POST",headers:{"x-csrf-token":csrf}});location.assign("/login")});
    function value(input,type){if(type==="checkbox")return input.checked;if(type==="multi_select")return [...input.selectedOptions].map(option=>option.value);return input.value}
    function payload(form,create){const fields=JSON.parse(form.dataset.fields||"[]"),result={};for(const field of fields){const input=form.elements[field.field_key];if(!input)continue;const target=["title","description","category","priority","source_url","environment","expected_behavior","actual_behavior","reproduction_steps"].includes(field.field_key)?result:(result.submission??={});target[field.field_key]=value(input,field.field_type)}if(create)result.project_id=form.elements.project_id.value;else result.submission_revision=Number(form.elements.submission_revision.value);return result}
    async function submit(form){if(form.dataset.submitting)return;form.dataset.submitting="true";const button=form.querySelector('button[type="submit"]'),error=form.querySelector(".error");button.disabled=true;error.textContent="";try{const create=form.dataset.create!==undefined,response=await fetch(create?"/api/tickets":"/api/tickets/"+encodeURIComponent(form.dataset.ticketId),{method:create?"POST":"PATCH",headers:{"content-type":"application/json","x-csrf-token":csrf},body:JSON.stringify(payload(form,create))});if(response.status===401)return location.assign("/login");if(response.status===409){error.textContent="This ticket changed. Reload it before saving; your edits are still here.";return}if(response.status===403||response.status===404){error.textContent="You no longer have access to this ticket or project.";return}const result=await response.json();if(!response.ok){error.textContent=result.fields?Object.entries(result.fields).map(([key,message])=>key+": "+message).join(" · "):result.error;return}location.assign("/tickets/"+encodeURIComponent(result.ticket.ticket_number))}catch{error.textContent="Saving failed. Your edits are still here."}finally{delete form.dataset.submitting;button.disabled=false}}
    document.querySelectorAll("[data-ticket-form]").forEach(form=>form.addEventListener("submit",event=>{event.preventDefault();submit(form)}));
    const dialog=document.querySelector("[data-delete-dialog]"),open=document.querySelector("[data-delete-ticket]");
    open?.addEventListener("click",()=>{dialog.showModal();dialog.querySelector("[data-cancel-delete]").focus()});
    dialog?.querySelector("[data-cancel-delete]")?.addEventListener("click",()=>dialog.close());
    dialog?.addEventListener("keydown",event=>{if(event.key!=="Tab")return;const items=[...dialog.querySelectorAll("button")].filter(item=>!item.disabled),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
    dialog?.querySelector("[data-confirm-delete]")?.addEventListener("click",async event=>{const button=event.currentTarget,error=dialog.querySelector(".error");let navigating=false;button.disabled=true;error.textContent="";try{const response=await fetch("/api/tickets/"+encodeURIComponent(dialog.dataset.ticketId),{method:"DELETE",headers:{"x-csrf-token":csrf}});if(response.status===401){navigating=true;return location.assign("/login")}if(response.ok){navigating=true;return location.assign("/tickets")}error.textContent=response.status===403||response.status===404?"You no longer have access to delete this ticket.":"Deleting failed. Try again."}catch{error.textContent="Deleting failed. Try again."}finally{if(!navigating)button.disabled=false}});
  `;
}
